POST http://localhost:10002/directors/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Im9sZWciLCJyb2xlIjoidXNlciIsImV4cCI6MTY1NzgyMzAzMX0.YBkX1mzUzL-NnCIAvjbD0Fm5FBUsbyRDLTyuKZ2eor4

{
  "name": "superka"
}

###

GET http://localhost:10002/directors/
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Iml2YW4iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE2NTc4MjIxMzh9.hSUFooTmpuNF01hTCI1Pa2TY_UzQPUjn7w2ldPczpyM
###

GET http://localhost:10002/directors/1
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Iml2YW4iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE2NTc4MjIxMzh9.hSUFooTmpuNF01hTCI1Pa2TY_UzQPUjn7w2ldPczpyM
###

PUT http://localhost:10002/directors/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Im9sZWciLCJyb2xlIjoidXNlciIsImV4cCI6MTY1NzgyMzAzMX0.YBkX1mzUzL-NnCIAvjbD0Fm5FBUsbyRDLTyuKZ2eor4

{
  "name": "superka"
}

###

DELETE http://localhost:10002/directors/1
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Im9sZWciLCJyb2xlIjoidXNlciIsImV4cCI6MTY1NzgyMzAzMX0.YBkX1mzUzL-NnCIAvjbD0Fm5FBUsbyRDLTyuKZ2eor4
###

PATCH http://localhost:10002/directors/2
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Im9sZWciLCJyb2xlIjoidXNlciIsImV4cCI6MTY1NzgyMzAzMX0.YBkX1mzUzL-NnCIAvjbD0Fm5FBUsbyRDLTyuKZ2eor4

{
  "name": "superka"
}

###